<?php
// $Id$

function democirc_circ_holds($user) {
  $items = array();
  $items[] = array(
    'ITEM_TYPE' => 'BOOK',
    'TITLE' => 'Structure and Interpretation of Computer Programs',
    'AUTHOR' => 'Abelson, Harold',
    'NOT_NEEDED_AFTER' => date('M j, Y', strtotime('+7 day')),
    'STATUS' => 'available',
    'PICKUP_LOCATION' => 'Circulation Desk',
    'QUEUE POSITION' => '',
    'DUE_DATE' => '',
    'NOTE' => '',
  );
  $items[] = array(
    'ITEM_TYPE' => 'BOOK',
    'TITLE' => 'Introduction to the Theory of Computation',
    'AUTHOR' => 'Sipser, Michael',
    'NOT_NEEDED_AFTER' => date('M j, Y', strtotime('+30 day')),
    'DUE_DATE' => date('M j, Y', strtotime('+14 day')),
    'STATUS' => 'unavailable',
    'QUEUE_POSITION' => '3',
    'NOTE' => '',
    'PICKUP_LOCATION' => '',
  );
  return $items;
}

function democirc_circ_charges($user) {
  $items = array();
  $items[] = array(
    'ITEM_TYPE' => 'BOOK',
    'TITLE' => 'Hackers and Painters: Big Ideas from the Computer Age',
    'AUTHOR' => 'Paul Graham',
    'STATUS' => 'charged',
    'DUE_DATE' => date('M j, Y', strtotime('+21 day')),
    'RENEW_PATH' => '',   // Should be in the form user/<uid>/circ/<module>/renew/<item identifier>
  );
  $items[] = array(
    'ITEM_TYPE' => 'BOOK',
    'TITLE' => 'ANSI Common LISP',
    'AUTHOR' => 'Paul Graham',
    'STATUS' => 'charged',
    'DUE_DATE' => date('M j, Y', strtotime('+7 day')),
    'RENEW_PATH' => '',   // Should be in the form user/<uid>/circ/<module>/renew/<item identifier>
  );
  $items[] = array(
    'ITEM_TYPE' => 'BOOK',
    'TITLE' => 'The Art of the Start: The Time-Tested, Battle-Hardened Guide for Anyone Starting Anything',
    'AUTHOR' => 'Guy Kawasaki',
    'STATUS' => 'charged',
    'DUE_DATE' => date('M j, Y', strtotime('-7 day')),
    'RENEW_PATH' => '',   // Should be in the form user/<uid>/circ/<module>/renew/<item identifier>
  );
  $items[] = array(
    'ITEM_TYPE' => 'BOOK',
    'TITLE' => 'A Plague of Rats and Rubbervines',
    'AUTHOR' => 'Yvonne Baskin',
    'STATUS' => 'charged',
    'DUE_DATE' => date('M j, Y', strtotime('-40 day')),
    'RENEW_PATH' => '',   // Should be in the form user/<uid>/circ/<module>/renew/<item identifier>
  );
 
  $items[] = array(
    'ITEM_TYPE' => 'BOOK',
    'TITLE' => 'Founders at Work',
    'AUTHOR' => 'Jessica Livingston',
    'STATUS' => 'recall',
    'DUE_DATE' => 'November 11, 2009',
    'NOTE' => 'Item recalled. The due date has been modified. Please return this item as soon as possible.',
    'RENEW_PATH' => '',   // Should be in the form user/<uid>/circ/<module>/renew/<item identifier>
  );

  return $items;
}

function democirc_circ_fines($user) {
  $items = array();
  $items[] = array(
    'ITEM_TYPE' => 'BOOK',
    'TITLE' => 'Create Your Own Economy: The Path to Prosperity in a Disordered World',
    'AUTHOR' => 'Tyler Cowen',
    'FINE_FEE_DESC' => 'Item Overdue',
    'FINE_FEE_AMOUNT' => '1500',
    'FINE_FEE_BALANCE' => '1500',
  );
  return $items;
}

